import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Alert } from '../../components/atoms/Alert';
import { Button } from '../../components/atoms/Button';
import { Checkbox } from '../../components/atoms/Checkbox';
import { FormField } from '../../components/atoms/FormField';
import { Input } from '../../components/atoms/Input';
import { Textarea } from '../../components/atoms/Textarea';
import { Spinner } from '../../components/atoms/Spinner';
import { ErrorPanel } from '../../components/molecules/ErrorPanel';
import { PageHeader } from '../../components/molecules/PageHeader';
import { api, jsonBody } from '../../lib/api';
type SettingsForm = { name: string; description: string; logoUrl: string; defaultPageSize: number; allowUserCreateIssue: boolean };
const empty: SettingsForm = { name: 'IssueFlow', description: '', logoUrl: '', defaultPageSize: 20, allowUserCreateIssue: true };
export function AdminSettingsPage() { const client = useQueryClient(); const [form, setForm] = useState(empty); const query = useQuery({ queryKey: ['admin-settings'], queryFn: () => api<SettingsForm>('/settings') }); useEffect(() => { if (query.data) setForm(query.data); }, [query.data]); const save = useMutation({ mutationFn: () => api<SettingsForm>('/admin/settings', { method: 'PUT', ...jsonBody(form) }), onSuccess: (data) => { setForm(data); void client.invalidateQueries({ queryKey: ['platform-settings-public'] }); } }); if (query.isPending) return <Spinner />; if (query.isError) return <div className="surface"><ErrorPanel message={query.error.message} /></div>; return <><PageHeader title="平台设置" description="配置平台品牌、分页和用户创建权限" /><form className="surface max-w-3xl space-y-5 p-5" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}>{save.error && <Alert message={save.error.message} />}{save.isSuccess && <Alert variant="success" message="平台设置已保存" />}<FormField label="平台名称" htmlFor="platform-name" required><Input id="platform-name" maxLength={100} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></FormField><FormField label="平台描述" htmlFor="platform-description"><Textarea id="platform-description" maxLength={500} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></FormField><FormField label="Logo URL" htmlFor="platform-logo" hint="留空将使用默认文本标识"><Input id="platform-logo" type="url" value={form.logoUrl} onChange={(e) => setForm({ ...form, logoUrl: e.target.value })} /></FormField><FormField label="默认每页数量" htmlFor="platform-page-size" hint="可设置 5–100"><Input id="platform-page-size" type="number" min={5} max={100} value={form.defaultPageSize} onChange={(e) => setForm({ ...form, defaultPageSize: Number(e.target.value) })} /></FormField><label className="flex min-h-11 cursor-pointer items-center gap-3 rounded-lg border p-3"><Checkbox checked={form.allowUserCreateIssue} onChange={(e) => setForm({ ...form, allowUserCreateIssue: e.target.checked })} /><span><span className="block text-sm font-semibold">允许普通用户创建 Issue</span><span className="block text-xs text-slate-500">关闭后仅管理员可创建新 Issue</span></span></label><div className="flex justify-end"><Button type="submit" loading={save.isPending} disabled={!form.name.trim() || form.defaultPageSize < 5 || form.defaultPageSize > 100} icon={<Save className="size-4" />}>保存设置</Button></div></form></>; }
