import { Bell, CircleDot, KeyRound, LayoutDashboard, LogOut, Menu, Settings, UserRound, X } from 'lucide-react';
import { useState } from 'react';
import { NavLink, Outlet } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { useAuth } from '../../features/auth/AuthProvider';
import { Avatar } from '../atoms/Avatar';

const navClass = ({ isActive }: { isActive: boolean }) => `flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm font-medium transition-colors ${isActive ? 'bg-brand-100 text-brand-900' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'}`;
export function AppShell() {
  const { user, settings, logout } = useAuth(); const [mobileOpen, setMobileOpen] = useState(false);
  const canAdmin = user?.role === 'ADMIN' || user?.roles?.includes('MANAGEMENT');
  const unread = useQuery({ queryKey: ['notifications-unread'], queryFn: () => api<{ unread: number }>('/notifications?unread=true&pageSize=1'), refetchInterval: 60_000 });
  const unreadCount = unread.data?.unread ?? 0;
  const close = () => setMobileOpen(false);
  const nav = <><NavLink to="/issues" onClick={close} className={navClass}><CircleDot className="size-5" aria-hidden="true" />Issues</NavLink><NavLink to="/notifications" onClick={close} className={navClass}><Bell className="size-5" aria-hidden="true" />通知{unreadCount > 0 && <span className="ml-auto rounded-full bg-red-600 px-1.5 text-xs text-white" aria-label={`${unreadCount} 条未读`}>{unreadCount}</span>}</NavLink><NavLink to="/settings/profile" onClick={close} className={navClass}><UserRound className="size-5" aria-hidden="true" />个人中心</NavLink><NavLink to="/settings/api-tokens" onClick={close} className={navClass}><KeyRound className="size-5" aria-hidden="true" />API Token</NavLink>{canAdmin && <NavLink to="/admin" onClick={close} className={navClass}><LayoutDashboard className="size-5" aria-hidden="true" />管理后台</NavLink>}</>;
  return <div className="min-h-screen bg-brand-50/60">
    <a href="#main-content" className="fixed left-3 top-2 z-[60] -translate-y-20 rounded bg-white px-3 py-2 shadow focus:translate-y-0">跳到主要内容</a>
    <header className="sticky top-0 z-40 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6 lg:px-8"><button onClick={() => setMobileOpen(true)} className="flex size-11 items-center justify-center rounded-lg hover:bg-slate-100 lg:hidden" aria-label="打开导航"><Menu className="size-5" aria-hidden="true" /></button><NavLink to="/issues" className="flex items-center gap-2 font-bold text-brand-900"><span className="flex size-9 items-center justify-center rounded-lg bg-brand-600 text-white"><CircleDot className="size-5" aria-hidden="true" /></span><span className="hidden sm:inline">{settings.platformName}</span></NavLink><nav className="ml-5 hidden items-center gap-1 lg:flex" aria-label="主导航">{nav}</nav><div className="ml-auto flex items-center gap-2"><NavLink to="/notifications" aria-label={unreadCount > 0 ? `通知，${unreadCount} 条未读` : '通知'} className="relative flex size-11 items-center justify-center rounded-lg text-slate-600 transition-colors hover:bg-slate-100 lg:hidden"><Bell className="size-5" aria-hidden="true" />{unreadCount > 0 && <span className="absolute right-0.5 top-0.5 min-w-4 rounded-full bg-red-600 px-1 text-center text-[10px] font-semibold leading-4 text-white ring-2 ring-white" aria-hidden="true">{unreadCount > 99 ? '99+' : unreadCount}</span>}</NavLink><NavLink to="/settings/profile" aria-label="个人中心" className="flex items-center gap-2 rounded-lg p-1 transition-colors hover:bg-slate-100"><Avatar name={user?.displayName || '用户'} src={user?.avatarUrl} /><div className="hidden text-left text-sm sm:block"><p className="max-w-32 truncate font-semibold">{user?.displayName}</p><p className="text-xs text-slate-500">{user?.role === 'ADMIN' ? '管理员' : `@${user?.username}`}</p></div></NavLink><button onClick={() => void logout()} className="flex size-11 items-center justify-center rounded-lg text-slate-600 hover:bg-slate-100" aria-label="退出登录"><LogOut className="size-5" aria-hidden="true" /></button></div></div></header>
    {mobileOpen && <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-slate-950/40" onClick={close} aria-label="关闭导航遮罩" /><aside className="relative h-full w-[min(84vw,320px)] bg-white p-4"><div className="mb-5 flex items-center justify-between"><span className="font-bold text-brand-900">{settings.platformName}</span><button onClick={close} className="flex size-11 items-center justify-center rounded-lg hover:bg-slate-100" aria-label="关闭导航"><X className="size-5" /></button></div><nav className="space-y-1" aria-label="移动端主导航">{nav}</nav>{canAdmin && <NavLink to="/admin/settings" onClick={close} className={`${navClass({ isActive: false })} mt-5 border-t pt-4`}><Settings className="size-5" />平台设置</NavLink>}</aside></div>}
    <main id="main-content" tabIndex={-1}><Outlet /></main>
  </div>;
}
