import { Search, SlidersHorizontal, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Label, Milestone, User } from '../../lib/types';
import { Button } from '../atoms/Button';
import { Input } from '../atoms/Input';
import { Select } from '../atoms/Select';
import { LabelFilter } from '../molecules/LabelFilter';
export interface Filters { q: string; status: string; assignee: string; author: string; label: string; milestone: string; sort: string }
export function FilterBar({ value, users, labels, milestones, onChange, onClear }: { value: Filters; users: User[]; labels: Label[]; milestones: Milestone[]; onChange: (next: Partial<Filters>) => void; onClear: () => void }) {
  const [search, setSearch] = useState(value.q); const [expanded, setExpanded] = useState(false);
  useEffect(() => setSearch(value.q), [value.q]);
  useEffect(() => { const timer = window.setTimeout(() => { if (search !== value.q) onChange({ q: search }); }, 350); return () => window.clearTimeout(timer); }, [search, value.q, onChange]);
  const active = Object.entries(value).some(([key, val]) => key !== 'sort' && key !== 'status' && Boolean(val));
  return <div className="border-b bg-slate-50 p-3"><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-slate-400" aria-hidden="true" /><Input value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" placeholder="搜索标题和内容" aria-label="搜索 Issue" /></div><Select value={value.status} onChange={(e) => onChange({ status: e.target.value })} className="sm:w-44" aria-label="状态"><option value="OPEN">开放（含待验收）</option><option value="CLOSED">已关闭</option><option value="ALL">全部状态</option></Select><Button type="button" variant="secondary" icon={<SlidersHorizontal className="size-4" />} onClick={() => setExpanded((v) => !v)} aria-expanded={expanded}>筛选</Button>{active && <Button type="button" variant="ghost" icon={<X className="size-4" />} onClick={onClear}>清除</Button>}</div>{expanded && <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><Select aria-label="作者" value={value.author} onChange={(e) => onChange({ author: e.target.value })}><option value="">全部作者</option>{users.map((u) => <option key={u.id} value={u.id}>{u.displayName}</option>)}</Select><Select aria-label="负责人" value={value.assignee} onChange={(e) => onChange({ assignee: e.target.value })}><option value="">全部负责人</option>{users.map((u) => <option key={u.id} value={u.id}>{u.displayName}</option>)}</Select><LabelFilter labels={labels} value={value.label} onChange={(label) => onChange({ label })} /><Select aria-label="里程碑" value={value.milestone} onChange={(e) => onChange({ milestone: e.target.value })}><option value="">全部里程碑</option>{milestones.map((m) => <option key={m.id} value={m.id}>{m.title}</option>)}</Select><Select aria-label="排序" value={value.sort} onChange={(e) => onChange({ sort: e.target.value })}><option value="updated-desc">最近更新</option><option value="created-desc">最新创建</option><option value="created-asc">最早创建</option></Select></div>}</div>;
}
