import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { vi } from 'vitest';
import { useState } from 'react';
import { FilterBar, type Filters } from './FilterBar';
const value: Filters = { q: '', status: 'OPEN', assignee: '', author: '', label: '', milestone: '', sort: 'updated-desc' };
describe('FilterBar', () => { it('将待验收归入开放，并使用明确的 ALL 值筛选全部状态', async () => { const user = userEvent.setup(); const onChange = vi.fn(); render(<FilterBar value={value} users={[]} labels={[]} milestones={[]} onChange={onChange} onClear={vi.fn()} />); expect(screen.getByRole('option', { name: '开放（含待验收）' })).toHaveValue('OPEN'); expect(screen.queryByRole('option', { name: '待验收' })).not.toBeInTheDocument(); await user.selectOptions(screen.getByRole('combobox', { name: '状态' }), 'ALL'); expect(onChange).toHaveBeenCalledWith({ status: 'ALL' }); await user.click(screen.getByRole('button', { name: '筛选' })); expect(screen.getByRole('combobox', { name: '作者' })).toBeVisible(); }); });

describe('FilterBar 标签筛选', () => { it('可搜索并组合多个标签', async () => { const user = userEvent.setup(); function Harness() { const [filters, setFilters] = useState(value); return <FilterBar value={filters} users={[]} labels={[{ id: 1, name: 'bug', description: '缺陷', color: 'd73a4a' }, { id: 2, name: 'enhancement', description: '改进', color: 'a2eeef' }]} milestones={[]} onChange={(next) => setFilters((current) => ({ ...current, ...next }))} onClear={() => undefined} />; } render(<Harness />); await user.click(screen.getByRole('button', { name: '筛选' })); await user.click(screen.getByText(/^标签$/)); await user.type(screen.getByRole('searchbox', { name: '搜索标签' }), 'bug'); await user.click(screen.getByRole('checkbox', { name: /bug/ })); await user.clear(screen.getByRole('searchbox', { name: '搜索标签' })); await user.click(screen.getByRole('checkbox', { name: /enhancement/ })); expect(screen.getByText('标签 · 2')).toBeVisible(); }); });
