import { CircleCheck, CircleDot, ClipboardCheck, MessageSquare, Pencil, Tag, UserRoundPlus } from 'lucide-react';
import type { TimelineEvent } from '../../lib/types';
import { formatDate } from '../../lib/format';
import { Avatar } from '../atoms/Avatar';
import { MarkdownRenderer } from '../molecules/MarkdownRenderer';
const icons = { COMMENT_CREATED: MessageSquare, COMMENT_EDITED: Pencil, COMMENT_DELETED: MessageSquare, ISSUE_CLOSED: CircleCheck, ISSUE_CLOSED_BY_YUNXIAO_COMMIT: CircleCheck, ISSUE_REOPENED: CircleDot, ISSUE_REOPENED_BY_YUNXIAO_COMMIT: CircleDot, ISSUE_AWAITING_ACCEPTANCE: ClipboardCheck, ISSUE_AWAITING_ACCEPTANCE_BY_YUNXIAO_COMMIT: ClipboardCheck, ISSUE_EDITED: Pencil, ASSIGNEES_CHANGED: UserRoundPlus, LABELS_CHANGED: Tag, MILESTONE_CHANGED: Tag };
const labels: Record<string, string> = { ISSUE_CREATED: '创建了 Issue', COMMENT_CREATED: '发表了评论', COMMENT_EDITED: '编辑了评论', COMMENT_DELETED: '删除了评论', ISSUE_CLOSED: '关闭了 Issue', ISSUE_CLOSED_BY_YUNXIAO_COMMIT: '通过云效提交关闭了 Issue', ISSUE_REOPENED: '重新打开了 Issue', ISSUE_REOPENED_BY_YUNXIAO_COMMIT: '通过云效提交重新打开了 Issue', ISSUE_AWAITING_ACCEPTANCE: '将 Issue 标记为待验收', ISSUE_AWAITING_ACCEPTANCE_BY_YUNXIAO_COMMIT: '通过云效提交将 Issue 标记为待验收', ISSUE_EDITED: '更新了 Issue', ASSIGNEES_CHANGED: '更新了负责人', LABELS_CHANGED: '更新了标签', MILESTONE_CHANGED: '更新了里程碑' };
export function Timeline({ events }: { events: TimelineEvent[] }) {
  return <ol className="space-y-4" aria-label="Issue 时间线">{events.map((event) => { const Icon = icons[event.type as keyof typeof icons] ?? CircleDot; const comment = event.comment; return <li key={event.id} className="relative flex gap-3"><div className="absolute bottom-[-1rem] left-[17px] top-9 w-px bg-slate-200 last:hidden" /><Avatar name={event.actor.displayName} src={event.actor.avatarUrl} /><div className={`min-w-0 flex-1 ${comment ? 'surface overflow-hidden' : 'py-1.5'}`}>{comment ? <><div className="border-b bg-slate-50 px-4 py-2 text-sm"><strong>{event.actor.displayName}</strong> 评论于 <time dateTime={event.createdAt}>{formatDate(event.createdAt)}</time>{comment.updatedAt && comment.updatedAt !== comment.createdAt && <span className="ml-2 text-xs text-slate-500">已编辑</span>}</div><div className="p-4"><MarkdownRenderer value={comment.body} emptyText="评论已删除" /></div></> : <p className="flex flex-wrap items-center gap-1.5 text-sm text-slate-600"><Icon className="size-4 text-brand-700" aria-hidden="true" /><strong className="text-slate-800">{event.actor.displayName}</strong>{labels[event.type] ?? '更新了 Issue'}<time className="text-xs text-slate-500" dateTime={event.createdAt}>{formatDate(event.createdAt)}</time></p>}</div></li>; })}</ol>;
}
