import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Pencil } from 'lucide-react';
import { useState } from 'react';
import { useLocation, useParams } from 'react-router-dom';
import { Alert } from '../components/atoms/Alert';
import { Badge } from '../components/atoms/Badge';
import { Button } from '../components/atoms/Button';
import { FormField } from '../components/atoms/FormField';
import { Input } from '../components/atoms/Input';
import { Modal } from '../components/atoms/Modal';
import { Spinner } from '../components/atoms/Spinner';
import { ErrorPanel } from '../components/molecules/ErrorPanel';
import { IssueStateBadge } from '../components/molecules/IssueStateBadge';
import { IssueStateActions } from '../components/molecules/IssueStateActions';
import { LabelPicker } from '../components/molecules/LabelPicker';
import { MarkdownEditor } from '../components/molecules/MarkdownEditor';
import { MarkdownRenderer } from '../components/molecules/MarkdownRenderer';
import { MilestonePicker } from '../components/molecules/MilestonePicker';
import { UserPicker } from '../components/molecules/UserPicker';
import { CommentComposer } from '../components/organisms/CommentComposer';
import { DevelopmentActivity } from '../components/organisms/DevelopmentActivity';
import { IssueSidebar } from '../components/organisms/IssueSidebar';
import { IssueAttachments } from '../components/organisms/IssueAttachments';
import { Timeline } from '../components/organisms/Timeline';
import { useAuth } from '../features/auth/AuthProvider';
import { useIssueMetadata } from '../features/issues/useIssueMetadata';
import { api, jsonBody } from '../lib/api';
import { formatDate } from '../lib/format';
import { normalizeIssue } from '../lib/normalize';
import type { Comment, Issue, TimelineEvent } from '../lib/types';
type IssueDetail = Issue & { timeline: TimelineEvent[]; comments: Comment[] };
type IssueUpdate = Partial<Issue> & { productOwnerIds?: number[]; developerOwnerIds?: number[]; labelIds?: number[]; milestoneId?: number | null };
export function IssueDetailPage() {
  const { number = '' } = useParams(); const location = useLocation(); const client = useQueryClient(); const { user } = useAuth(); const metadata = useIssueMetadata(); const [editing, setEditing] = useState(false); const [relationsEditing, setRelationsEditing] = useState(false); const [editTitle, setEditTitle] = useState(''); const [editBody, setEditBody] = useState(''); const [productOwnerIds, setProductOwnerIds] = useState<number[]>([]); const [developerOwnerIds, setDeveloperOwnerIds] = useState<number[]>([]); const [labelIds, setLabelIds] = useState<number[]>([]); const [milestoneId, setMilestoneId] = useState<number | ''>('');
  const issueQuery = useQuery({ queryKey: ['issue', number], queryFn: async () => { const raw = await api<IssueDetail>(`/issues/${number}`); return { ...normalizeIssue(raw), timeline: raw.timeline, comments: raw.comments } as IssueDetail; } });
  const refresh = () => { void client.invalidateQueries({ queryKey: ['issue', number] }); };
  const update = useMutation({ mutationFn: (value: IssueUpdate) => api<Issue>(`/issues/${number}`, { method: 'PATCH', ...jsonBody({ ...value, status: undefined, ...(value.status ? { state: value.status } : {}), updatedAt: issueQuery.data?.updatedAt }) }), onSuccess: () => { setEditing(false); setRelationsEditing(false); refresh(); void client.invalidateQueries({ queryKey: ['issues'] }); } });
  const comment = useMutation({ mutationFn: (body: string) => api(`/issues/${number}/comments`, { method: 'POST', ...jsonBody({ body }) }), onSuccess: refresh });
  const subscription = useMutation({ mutationFn: (subscribed: boolean) => api(`/issues/${number}/subscription`, { method: 'PUT', ...jsonBody({ subscribed: !subscribed }) }), onSuccess: refresh });
  if (issueQuery.isPending) return <div className="page-container"><Spinner label="正在加载 Issue" /></div>;
  if (issueQuery.isError) return <div className="page-container surface"><ErrorPanel title={issueQuery.error instanceof Error && 'status' in issueQuery.error && issueQuery.error.status === 404 ? 'Issue 不存在' : '加载失败'} message={issueQuery.error.message} onRetry={() => void issueQuery.refetch()} /></div>;
  const issue = issueQuery.data;
  const mergedEvents: TimelineEvent[] = [...issue.timeline.filter((event) => !['COMMENT_CREATED', 'COMMENT_EDITED'].includes(event.type)), ...issue.comments.filter((item) => !item.deletedAt).map((item) => ({ id: -item.id, type: 'COMMENT_CREATED', actor: item.author, createdAt: item.createdAt, comment: item }))].sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
  const timeline = { isPending: false, isError: false, data: mergedEvents, error: new Error('时间线加载失败') };
  const canEdit = user?.role === 'ADMIN' || user?.roles?.includes('MANAGEMENT') || user?.id === issue.author.id; const canTransition = canEdit || issue.assignees.some((a) => a.id === user?.id);
  const openRelations = () => { setProductOwnerIds(issue.productOwners.map((item) => item.id)); setDeveloperOwnerIds(issue.developerOwners.map((item) => item.id)); setLabelIds(issue.labels.map((item) => item.id)); setMilestoneId(issue.milestone?.id ?? ''); setRelationsEditing(true); };
  const attachmentWarning = (location.state as { attachmentWarning?: string } | null)?.attachmentWarning;
  return <div className="page-container">{attachmentWarning && <div className="mb-4"><Alert message={attachmentWarning} /></div>}<div className="mb-5 border-b pb-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="break-words text-2xl font-bold tracking-tight sm:text-3xl">{issue.title} <span className="font-normal text-slate-400">#{issue.number}</span></h1>{issue.isProductIssue && <Badge color="EA580C">产品 Issue</Badge>}</div><div className="mt-3 flex flex-wrap items-center gap-2 text-sm text-slate-600"><IssueStateBadge status={issue.status} /><span><strong>{issue.author.displayName}</strong> 创建于 {formatDate(issue.createdAt)}</span></div></div><div className="flex shrink-0 flex-wrap gap-2">{canEdit && <Button variant="secondary" icon={<Pencil className="size-4" />} onClick={() => { setEditTitle(issue.title); setEditBody(issue.body ?? ''); setEditing(true); }}>编辑</Button>}{canTransition && <IssueStateActions status={issue.status} loading={update.isPending} onChange={(status) => update.mutate({ status })} />}</div></div></div><div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="min-w-0 space-y-5"><article className="surface"><header className="flex items-center gap-2 border-b bg-slate-50 px-4 py-3 text-sm"><strong>{issue.author.displayName}</strong><span className="text-slate-500">描述了这个 Issue</span></header><div className="p-4"><MarkdownRenderer value={issue.body} emptyText="未提供描述" /></div></article><IssueAttachments issueId={issue.id} /><DevelopmentActivity issueId={issue.id} />{timeline.isPending ? <Spinner label="正在加载时间线" /> : timeline.isError ? <Alert message={timeline.error.message} /> : <Timeline events={timeline.data} />}<CommentComposer loading={comment.isPending} error={comment.error?.message} onSubmit={(body) => comment.mutate(body)} /></div><IssueSidebar issue={issue} subscribing={subscription.isPending} onEditRelations={canTransition ? openRelations : undefined} onToggleSubscribe={() => subscription.mutate(!!issue.subscribed)} /></div><Modal open={editing} title="编辑 Issue" onClose={() => setEditing(false)}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (editTitle.trim()) update.mutate({ title: editTitle.trim(), body: editBody }); }}>{update.error && <Alert message={update.error.message} />}<FormField label="标题" htmlFor="edit-title" required><Input id="edit-title" maxLength={200} value={editTitle} onChange={(e) => setEditTitle(e.target.value)} /></FormField><FormField label="描述" htmlFor="edit-body"><MarkdownEditor id="edit-body" value={editBody} onChange={setEditBody} minRows={7} /></FormField><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setEditing(false)}>取消</Button><Button type="submit" loading={update.isPending} disabled={!editTitle.trim()}>保存更改</Button></div></form></Modal><Modal open={relationsEditing} title="编辑负责人和分类" onClose={() => setRelationsEditing(false)}><form className="space-y-5" onSubmit={(e) => { e.preventDefault(); update.mutate({ productOwnerIds, developerOwnerIds, labelIds, milestoneId: milestoneId || null }); }}>{update.error && <Alert message={update.error.message} />}{metadata.loading ? <Spinner label="正在加载分类数据" /> : <><FormField label="产品负责人" htmlFor="relation-product-owners"><UserPicker users={metadata.users.filter((item) => item.roles?.includes('PRODUCT'))} value={productOwnerIds} onChange={setProductOwnerIds} ariaLabel="选择产品负责人" /></FormField><FormField label="开发负责人" htmlFor="relation-developer-owners"><UserPicker users={metadata.users.filter((item) => item.roles?.includes('DEVELOPMENT'))} value={developerOwnerIds} onChange={setDeveloperOwnerIds} ariaLabel="选择开发负责人" /></FormField><FormField label="标签" htmlFor="relation-labels"><LabelPicker labels={metadata.labels} value={labelIds} onChange={setLabelIds} /></FormField><FormField label="里程碑" htmlFor="relation-milestone"><MilestonePicker milestones={metadata.milestones} value={milestoneId} onChange={setMilestoneId} /></FormField><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setRelationsEditing(false)}>取消</Button><Button type="submit" loading={update.isPending}>保存分类</Button></div></>}</form></Modal></div>;
}
